### ISSUE TITLE
Only the font shows up

### ISSUE THREAD

**Issue by kidfur** [winterClover/Pesterchum-Discord-Theme#1]
When i use the theme on the latest version of Discord, only the font shows up. I tried changing it to light mode and made sure I didn't have any other themes also on but nothing fixed it

**Comment by GriffinHines** [comment]
Try this updated fork: https://github.com/luminaryFlowers/Pesterchum-Discord-Theme

**Comment by winterClover** [comment]
yeag, please use the newer fork, I'm not updating this no more.
